float soma(float var1, float var2);
float subtracao(float var1, float var2);
float divisao(float var1, float var2);
float multiplicacao(float var1, float var2);
int fatorial(int var1);
int primo(int var1);
float cosseno(float var1);
float medianotas(float var1, float var2);
float raizx1(float a, float b, float c);
float raizx2(float a, float b, float c);
float triangulo(float l1, float l2, float l3);
float tresnotas(float nota1, float nota2);
float af(float complemento);
float cidades(float var1, float var2, float var3, float var4);
